// <auto-generated />
namespace Microsoft.Framework.DependencyInjection
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.Framework.DependencyInjection.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// Unable to resolve service for type '{0}' while attempting to activate '{1}'.
        /// </summary>
        internal static string CannotResolveService
        {
            get { return GetString("CannotResolveService"); }
        }

        /// <summary>
        /// Unable to resolve service for type '{0}' while attempting to activate '{1}'.
        /// </summary>
        internal static string FormatCannotResolveService(object p0, object p1)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("CannotResolveService"), p0, p1);
        }

        /// <summary>
        /// A circular dependency was detected for the service of type '{0}'.
        /// </summary>
        internal static string CircularDependencyException
        {
            get { return GetString("CircularDependencyException"); }
        }

        /// <summary>
        /// A circular dependency was detected for the service of type '{0}'.
        /// </summary>
        internal static string FormatCircularDependencyException(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("CircularDependencyException"), p0);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
