//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Gen.OptionsValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Gen.OptionsValidation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} already implements the Validate method.
        /// </summary>
        internal static string AlreadyImplementsValidateMethodMessage {
            get {
                return ResourceManager.GetString("AlreadyImplementsValidateMethodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type already includes an implementation of the `Validate` method.
        /// </summary>
        internal static string AlreadyImplementsValidateMethodTitle {
            get {
                return ResourceManager.GetString("AlreadyImplementsValidateMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OptionsValidator] cannot be applied to static class {0}.
        /// </summary>
        internal static string CantBeStaticClassMessage {
            get {
                return ResourceManager.GetString("CantBeStaticClassMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `OptionsValidatorAttribute` can&apos;t be applied to a static class.
        /// </summary>
        internal static string CantBeStaticClassTitle {
            get {
                return ResourceManager.GetString("CantBeStaticClassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use [ValidateObjectMembers] or [ValidateEnumeratedItems] on fields or properties with open generic type {0}.
        /// </summary>
        internal static string CantUseWithGenericTypesMessage {
            get {
                return ResourceManager.GetString("CantUseWithGenericTypesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use `ValidateObjectMembersAttribute` or `ValidateEnumeratedItemsAttribute` on fields or properties with open generic types.
        /// </summary>
        internal static string CantUseWithGenericTypesTitle {
            get {
                return ResourceManager.GetString("CantUseWithGenericTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a circular type reference involving type {0} preventing it from being used for static validation.
        /// </summary>
        internal static string CircularTypeReferencesMessage {
            get {
                return ResourceManager.GetString("CircularTypeReferencesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported circular references in model types.
        /// </summary>
        internal static string CircularTypeReferencesTitle {
            get {
                return ResourceManager.GetString("CircularTypeReferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} does not implement the required IValidateOptions&lt;{1}&gt; interface.
        /// </summary>
        internal static string DoesntImplementIValidateOptionsMessage {
            get {
                return ResourceManager.GetString("DoesntImplementIValidateOptionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type annotated with `OptionsValidatorAttribute` doesn&apos;t implement the necessary interface.
        /// </summary>
        internal static string DoesntImplementIValidateOptionsTitle {
            get {
                return ResourceManager.GetString("DoesntImplementIValidateOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t apply validation attributes to private field or property {0}.
        /// </summary>
        internal static string MemberIsInaccessibleMessage {
            get {
                return ResourceManager.GetString("MemberIsInaccessibleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t validate private fields or properties.
        /// </summary>
        internal static string MemberIsInaccessibleTitle {
            get {
                return ResourceManager.GetString("MemberIsInaccessibleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has no fields or properties to validate, referenced from member {1}.
        /// </summary>
        internal static string NoEligibleMemberMessage {
            get {
                return ResourceManager.GetString("NoEligibleMemberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has no fields or properties to validate, referenced by type {1}.
        /// </summary>
        internal static string NoEligibleMembersFromValidatorMessage {
            get {
                return ResourceManager.GetString("NoEligibleMembersFromValidatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type has no fields or properties to validate.
        /// </summary>
        internal static string NoEligibleMembersFromValidatorTitle {
            get {
                return ResourceManager.GetString("NoEligibleMembersFromValidatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A member type has no fields or properties to validate.
        /// </summary>
        internal static string NoEligibleMemberTitle {
            get {
                return ResourceManager.GetString("NoEligibleMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ValidateEnumeratedItems] cannot be used on members of type {0} as it doesn&apos;t implement IEnumerable&lt;T&gt;.
        /// </summary>
        internal static string NotEnumerableTypeMessage {
            get {
                return ResourceManager.GetString("NotEnumerableTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member type is not enumerable.
        /// </summary>
        internal static string NotEnumerableTypeTitle {
            get {
                return ResourceManager.GetString("NotEnumerableTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null validator type specified in [ValidateObjectMembers] or [ValidateEnumeratedItems] attributes.
        /// </summary>
        internal static string NullValidatorTypeMessage {
            get {
                return ResourceManager.GetString("NullValidatorTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null validator type specified for the `ValidateObjectMembersAttribute` or `ValidateEnumeratedItemsAttribute` attributes.
        /// </summary>
        internal static string NullValidatorTypeTitle {
            get {
                return ResourceManager.GetString("NullValidatorTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has validation annotations, but member {1} doesn&apos;t specify [ValidateEnumeratedItems] which could be an oversight.
        /// </summary>
        internal static string PotentiallyMissingEnumerableValidationMessage {
            get {
                return ResourceManager.GetString("PotentiallyMissingEnumerableValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member potentially missing enumerable validation.
        /// </summary>
        internal static string PotentiallyMissingEnumerableValidationTitle {
            get {
                return ResourceManager.GetString("PotentiallyMissingEnumerableValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has validation annotations, but member {1} doesn&apos;t specify [ValidateObjectMembers] which could be an oversight.
        /// </summary>
        internal static string PotentiallyMissingTransitiveValidationMessage {
            get {
                return ResourceManager.GetString("PotentiallyMissingTransitiveValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member potentially missing transitive validation.
        /// </summary>
        internal static string PotentiallyMissingTransitiveValidationTitle {
            get {
                return ResourceManager.GetString("PotentiallyMissingTransitiveValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator type {0} doesn&apos;t have a parameterless constructor.
        /// </summary>
        internal static string ValidatorsNeedSimpleConstructorMessage {
            get {
                return ResourceManager.GetString("ValidatorsNeedSimpleConstructorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validators used for transitive or enumerable validation must have a constructor with no parameters.
        /// </summary>
        internal static string ValidatorsNeedSimpleConstructorTitle {
            get {
                return ResourceManager.GetString("ValidatorsNeedSimpleConstructorTitle", resourceCulture);
            }
        }
    }
}
