// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace Microsoft.Extensions.AI;

/// <summary>
/// Interface for a client that generates images from text prompts.
/// </summary>
[Experimental("MEAI001")]
public interface ITextToImageClient : IDisposable
{
    /// <summary>
    /// Sends a text prompt to the model and returns the generated image as a <see cref="TextToImageResponse"/>.
    /// </summary>
    /// <param name="prompt">The prompt to guide the image generation.</param>
    /// <param name="options">The text to image options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>The images generated by the client.</returns>
    Task<TextToImageResponse> GenerateImagesAsync(string prompt, TextToImageOptions? options, CancellationToken cancellationToken = default);

    /// <summary>
    /// Generates a new image based on the original image and the specified prompt.
    /// </summary>
    /// <param name="originalImage">The single image to base edits on.</param>
    /// <param name="prompt">The prompt to guide the image generation.</param>
    /// <param name="options">The text to image options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>The images generated by the client.</returns>
    Task<TextToImageResponse> GenerateEditImageAsync(Stream originalImage, string prompt, TextToImageOptions? options, CancellationToken cancellationToken = default);

    /// <summary>
    /// Generates a new image based on the original image and the specified prompt.
    /// </summary>
    /// <param name="originalImage">The single image to base edits on.</param>
    /// <param name="prompt">The prompt to guide the image generation.</param>
    /// <param name="options">The text to image options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>The images generated by the client.</returns>
    Task<TextToImageResponse> GenerateEditImageAsync(Uri originalImage, string prompt, TextToImageOptions? options, CancellationToken cancellationToken = default);

    /// <summary>Asks the <see cref="ITextToImageClient"/> for an object of the specified type <paramref name="serviceType"/>.</summary>
    /// <param name="serviceType">The type of object being requested.</param>
    /// <param name="serviceKey">An optional key that can be used to help identify the target service.</param>
    /// <returns>The found object, otherwise <see langword="null"/>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="serviceType"/> is <see langword="null"/>.</exception>
    /// <remarks>
    /// The purpose of this method is to allow for the retrieval of strongly typed services that might be provided by the <see cref="ITextToImageClient"/>,
    /// including itself or any services it might be wrapping.
    /// </remarks>
    object? GetService(Type serviceType, object? serviceKey = null);
}
