// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Shared.Diagnostics;

namespace Microsoft.Extensions.AI;

/// <summary>Extensions for <see cref="ITextToImageClient"/>.</summary>
[Experimental("MEAI001")]
public static class TextToImageClientExtensions
{
    /// <summary>Asks the <see cref="ITextToImageClient"/> for an object of type <typeparamref name="TService"/>.</summary>
    /// <typeparam name="TService">The type of the object to be retrieved.</typeparam>
    /// <param name="client">The client.</param>
    /// <param name="serviceKey">An optional key that can be used to help identify the target service.</param>
    /// <returns>The found object, otherwise <see langword="null"/>.</returns>
    /// <remarks>
    /// The purpose of this method is to allow for the retrieval of strongly typed services that may be provided by the <see cref="ITextToImageClient"/>,
    /// including itself or any services it might be wrapping.
    /// </remarks>
    public static TService? GetService<TService>(this ITextToImageClient client, object? serviceKey = null)
    {
        _ = Throw.IfNull(client);

        return (TService?)client.GetService(typeof(TService), serviceKey);
    }

    /// <summary>Generates text from speech providing a single audio speech <see cref="DataContent"/>.</summary>
    /// <param name="client">The client.</param>
    /// <param name="originalImage">The single image to base edits on.</param>
    /// <param name="prompt">The prompt to guide the image generation.</param>
    /// <param name="options">The text to image options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>The images generated by the client.</returns>
    public static Task<TextToImageResponse> GenerateEditImageAsync(
        this ITextToImageClient client,
        DataContent originalImage,
        string prompt,
        TextToImageOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        _ = Throw.IfNull(client);
        _ = Throw.IfNull(originalImage);

        var imageStream = MemoryMarshal.TryGetArray(originalImage.Data, out var array) ?
            new MemoryStream(array.Array!, array.Offset, array.Count) :
            new MemoryStream(originalImage.Data.ToArray());

        return client.GenerateEditImageAsync(imageStream, prompt, options, cancellationToken);
    }

    /// <summary>Generates text from speech providing a single audio speech <see cref="DataContent"/>.</summary>
    /// <param name="client">The client.</param>
    /// <param name="originalImage">The single image to base edits on.</param>
    /// <param name="prompt">The prompt to guide the image generation.</param>
    /// <param name="options">The text to image options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>The images generated by the client.</returns>
    public static Task<TextToImageResponse> GenerateEditImageAsync(
        this ITextToImageClient client,
        UriContent originalImage,
        string prompt,
        TextToImageOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        _ = Throw.IfNull(client);
        _ = Throw.IfNull(originalImage);

        return client.GenerateEditImageAsync(originalImage.Uri, prompt, options, cancellationToken);
    }

    /// <summary>Generates text from speech providing a single audio speech <see cref="DataContent"/>.</summary>
    /// <param name="client">The client.</param>
    /// <param name="originalImage">The single image to base edits on.</param>
    /// <param name="prompt">The prompt to guide the image generation.</param>
    /// <param name="options">The text to image options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>The images generated by the client.</returns>
    public static Task<TextToImageResponse> GenerateEditImageAsync(
        this ITextToImageClient client,
        AIContent originalImage,
        string prompt,
        TextToImageOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        _ = Throw.IfNull(client);
        _ = Throw.IfNull(originalImage);

        return originalImage switch
        {
            DataContent dataContent => client.GenerateEditImageAsync(dataContent, prompt, options, cancellationToken),
            UriContent uriContent => client.GenerateEditImageAsync(uriContent, prompt, options, cancellationToken),
            _ => throw new ArgumentException("Unsupported content type for image editing.", nameof(originalImage)),
        };
    }
}
