id: untriaged
name: Automatically apply and remove the untriaged label
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: Add untriaged label to new/reopened issues without a milestone
      if:
      - payloadType: Issues
      - or:
        - isAction:
            action: Opened
        - isAction:
            action: Reopened
      - isOpen
      - not: isPartOfAnyMilestone
      - not:
          hasLabel:
            label: untriaged
      then:
      - addLabel:
          label: untriaged

    - description: Remove untriaged label from closed issues
      if:
      - payloadType: Issues
      - hasLabel:
          label: untriaged
      - or:
        - isAction:
            action: Closed
      then:
      - removeLabel:
          label: untriaged
