trigger:
- master
- release/*

name: $(Date:yyMMdd)-$(Rev:rr)

resources:
  repositories:
  - repository: buildtools
    type: git
    name: aspnet-BuildTools
    ref: refs/heads/release/2.1

jobs:
- template: .azure/templates/project-ci.yml@buildtools
  parameters:
    codeSign: true
    buildArgs: |
      '/p:PublishBlobFeedKey=$(PB_PublishBlobFeedKey)'
