#pragma checksum "TestFiles/IntegrationTests/ComponentIntegrationTest/BasicTest.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "47f616cdc7ec75674c74246619b0e6118ef227e4"
// <auto-generated/>
#pragma warning disable 1591
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
    public class BasicTest : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
            builder.AddMarkupContent(0, "Hello world\r\n<span class=\"content\"></span>");
        }
        #pragma warning restore 1998
#line 4 "TestFiles/IntegrationTests/ComponentIntegrationTest/BasicTest.razor"
            
    string SomeProperty { get; set; }

#line default
#line hidden
    }
}
#pragma warning restore 1591
