// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
    using Microsoft.AspNetCore.Components.RenderTree;
    public class TestComponent : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
#line 4 "x:\dir\subdir\Test\TestComponent.cshtml"
   RenderChildComponent(builder); 

#line default
#line hidden
        }
        #pragma warning restore 1998
#line 6 "x:\dir\subdir\Test\TestComponent.cshtml"
            
    void RenderChildComponent(RenderTreeBuilder builder)
    {

#line default
#line hidden
        builder.AddContent(0, "        ");
        builder.OpenComponent<Test.MyComponent>(1);
        builder.CloseComponent();
        builder.AddContent(2, "\r\n");
#line 10 "x:\dir\subdir\Test\TestComponent.cshtml"
    }

#line default
#line hidden
    }
}
#pragma warning restore 1591
