// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Microsoft.Extensions.AI;

/// <summary>Represents a audio transcription client.</summary>
/// <remarks>
/// <para>
/// Unless otherwise specified, all members of <see cref="IAudioTranscriptionClient"/> are thread-safe for concurrent use.
/// It is expected that all implementations of <see cref="IAudioTranscriptionClient"/> support being used by multiple requests concurrently.
/// </para>
/// <para>
/// However, implementations of <see cref="IAudioTranscriptionClient"/> might mutate the arguments supplied to <see cref="TranscribeAsync"/> and
/// <see cref="TranscribeStreamingAsync"/>, such as by configuring the options instance. Thus, consumers of the interface either should avoid
/// using shared instances of these arguments for concurrent invocations or should otherwise ensure by construction that no
/// <see cref="IAudioTranscriptionClient"/> instances are used which might employ such mutation. For example, the ConfigureOptions method be
/// provided with a callback that could mutate the supplied options argument, and that should be avoided if using a singleton options instance.
/// </para>
/// </remarks>
public interface IAudioTranscriptionClient : IDisposable
{
    /// <summary>Sends audio contents to the model and returns the transcriptions.</summary>
    /// <param name="audioContents">The list of audio contents to send.</param>
    /// <param name="options">The audio transcription options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>The transcriptions generated by the client.</returns>
    Task<AudioTranscriptionResponse> TranscribeAsync(
        IList<IAsyncEnumerable<DataContent>> audioContents,
        AudioTranscriptionOptions? options = null,
        CancellationToken cancellationToken = default);

    /// <summary>Sends audio contents to the model and streams back the transcriptions.</summary>
    /// <param name="audioContents">The list of audio contents to send.</param>
    /// <param name="options">The audio transcription options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>The response messages generated by the client.</returns>
    IAsyncEnumerable<AudioTranscriptionResponseUpdate> TranscribeStreamingAsync(
        IList<IAsyncEnumerable<DataContent>> audioContents,
        AudioTranscriptionOptions? options = null,
        CancellationToken cancellationToken = default);

    /// <summary>Asks the <see cref="IAudioTranscriptionClient"/> for an object of the specified type <paramref name="serviceType"/>.</summary>
    /// <param name="serviceType">The type of object being requested.</param>
    /// <param name="serviceKey">An optional key that can be used to help identify the target service.</param>
    /// <returns>The found object, otherwise <see langword="null"/>.</returns>
    /// <remarks>
    /// The purpose of this method is to allow for the retrieval of strongly typed services that might be provided by the <see cref="IAudioTranscriptionClient"/>,
    /// including itself or any services it might be wrapping.
    /// </remarks>
    object? GetService(Type serviceType, object? serviceKey = null);
}
