blank_issues_enabled: true
contact_links:
  - name: Issue with ASP.NET Core
    url:  https://github.com/dotnet/aspnetcore/issues/new/choose
    about: Please open issues relating to ASP.NET Core in dotnet/aspnetcore.
  - name: Issue with .NET runtime or core .NET libraries
    url:  https://github.com/dotnet/runtime/issues/new/choose
    about: Please open issues with the .NET runtime or core in their repo
  - name: Issue with .NET SDK
    url:  https://github.com/dotnet/sdk/issues/new/choose
    about: Please open issues relating to the .NET SDK in dotnet/sdk.
