<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Microsoft.Extensions.DocumentExtraction</RootNamespace>
    <Description>Unit tests for Microsoft.Extensions.DocumentExtraction.Abstractions.</Description>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);MEDE0001;CA1063;CA1861;CA2201;VSTHRD003;S104</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <InjectDiagnosticAttributesOnLegacy>true</InjectDiagnosticAttributesOnLegacy>
    <InjectCompilerFeatureRequiredOnLegacy>true</InjectCompilerFeatureRequiredOnLegacy>
    <InjectRequiredMemberOnLegacy>true</InjectRequiredMemberOnLegacy>
    <InjectIsExternalInitOnLegacy>true</InjectIsExternalInitOnLegacy>
    <InjectStringSyntaxAttributeOnLegacy>true</InjectStringSyntaxAttributeOnLegacy>
    <InjectFilePolyfillsOnLegacy>true</InjectFilePolyfillsOnLegacy>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory.Data" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Libraries\Microsoft.Extensions.DocumentExtraction.Abstractions\Microsoft.Extensions.DocumentExtraction.Abstractions.csproj" ProjectUnderTest="true" />
  </ItemGroup>
</Project>
