// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Microsoft.Extensions.AI;

/// <summary>
/// Represents the results of invoking a code interpreter or execution tool.
/// </summary>
public sealed class CodeExecutionResultContent : AIContent
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CodeExecutionResultContent"/> class.
    /// </summary>
    public CodeExecutionResultContent()
    {
    }

    /// <summary>Gets or sets inputs provided to the code execution tool.</summary>
    public IList<AIContent>? Inputs { get; set; }

    /// <summary>Gets or sets a list of content generated as part of executing code.</summary>
    /// <remarks>
    /// This property contains the result of the code interpreter or execution tool. It can include various types of content,
    /// including standard output from the code execution (which is represented as <see cref="TextContent"/>), errors emitted by
    /// the tool (represented via <see cref="ErrorContent"/>), and any other content generated by
    /// the tool (typically represented via either <see cref="DataContent"/>, <see cref="UriContent"/>, or <see cref="HostedFileContent"/>).
    /// </remarks>
    public IList<AIContent>? Outputs { get; set; }

    /// <summary>Gets the tool's output.</summary>
    /// <remarks>This is a concatenation of all <see cref="TextContent"/> contained in <see cref="Outputs"/>.</remarks>
    [JsonIgnore]
    public string Text => Outputs?.ConcatText() ?? string.Empty;

}
