// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.DataIngestion.Tests;
using Microsoft.Extensions.VectorData;
using Xunit;

namespace Microsoft.Extensions.DataIngestion.Writers.Tests;

public abstract class VectorStoreWriterTests
{
    [Fact]
    public async Task CanWriteChunksWithCustomDefinition()
    {
        string documentId = Guid.NewGuid().ToString();

        using TestEmbeddingGenerator<AIContent> testEmbeddingGenerator = new();
        using VectorStore vectorStore = CreateVectorStore(testEmbeddingGenerator);

        // User creates their own definition without using CreateDefaultCollectionDefinition,
        // using custom storage names to prove they can map to a pre-existing collection schema.
        VectorStoreCollectionDefinition definition = new()
        {
            Properties =
            {
                new VectorStoreKeyProperty(nameof(IngestionChunkVectorRecord.Key), typeof(Guid)) { StorageName = "custom_key", IsAutoGenerated = true },
                new VectorStoreVectorProperty<AIContent>(nameof(IngestionChunkVectorRecord.Embedding), TestEmbeddingGenerator<AIContent>.DimensionCount)
                {
                    StorageName = "custom_embedding",
                },
                new VectorStoreDataProperty(nameof(IngestionChunkVectorRecord.SerializedContent), typeof(string)) { StorageName = "custom_content" },
                new VectorStoreDataProperty(nameof(IngestionChunkVectorRecord.Context), typeof(string)) { StorageName = "custom_context" },
                new VectorStoreDataProperty(nameof(IngestionChunkVectorRecord.DocumentId), typeof(string))
                {
                    StorageName = "custom_documentid",
                    IsIndexed = true,
                },
            },
        };

        VectorStoreCollection<Guid, IngestionChunkVectorRecord> collection = vectorStore.GetCollection<Guid, IngestionChunkVectorRecord>("chunks-custom", definition);

        using VectorStoreWriter<IngestionChunkVectorRecord> writer = new(collection);

        IngestionDocument document = new(documentId);
        IngestionChunk chunk = TestChunkFactory.CreateChunk("custom schema content", document);

        List<IngestionChunk> chunks = [chunk];

        await writer.WriteAsync(chunks.ToAsyncEnumerable());

        IngestionChunkVectorRecord record = await writer.VectorStoreCollection
            .GetAsync(filter: record => record.DocumentId == documentId, top: 1)
            .SingleAsync();

        Assert.NotNull(record);
        Assert.NotEqual(Guid.Empty, record.Key);
        Assert.Equal(documentId, record.DocumentId);
        Assert.NotEmpty(record.SerializedContent);
    }

    [Fact]
    public async Task CanWriteChunks()
    {
        string documentId = Guid.NewGuid().ToString();

        using TestEmbeddingGenerator<AIContent> testEmbeddingGenerator = new();
        using VectorStore vectorStore = CreateVectorStore(testEmbeddingGenerator);

        VectorStoreCollection<Guid, IngestionChunkVectorRecord> collection = vectorStore.GetIngestionRecordCollection<IngestionChunkVectorRecord>(
            "chunks", TestEmbeddingGenerator<AIContent>.DimensionCount);

        using VectorStoreWriter<IngestionChunkVectorRecord> writer = new(collection);

        IngestionDocument document = new(documentId);
        IngestionChunk chunk = TestChunkFactory.CreateChunk("some content", document);

        List<IngestionChunk> chunks = [chunk];

        Assert.False(testEmbeddingGenerator.WasCalled);
        await writer.WriteAsync(chunks.ToAsyncEnumerable());

        IngestionChunkVectorRecord record = await writer.VectorStoreCollection
            .GetAsync(filter: record => record.DocumentId == documentId, top: 1)
            .SingleAsync();

        Assert.NotNull(record);
        Assert.NotEqual(Guid.Empty, record.Key);
        Assert.Equal(documentId, record.DocumentId);
        Assert.NotEmpty(record.SerializedContent);
        Assert.True(testEmbeddingGenerator.WasCalled);
    }

    [Fact]
    public async Task CanWriteChunksWithMetadata()
    {
        string documentId = Guid.NewGuid().ToString();

        using TestEmbeddingGenerator<AIContent> testEmbeddingGenerator = new();
        using VectorStore vectorStore = CreateVectorStore(testEmbeddingGenerator);

        VectorStoreCollection<Guid, TestChunkRecordWithMetadata> collection = vectorStore.GetIngestionRecordCollection<TestChunkRecordWithMetadata>(
            "chunks-meta", TestEmbeddingGenerator<AIContent>.DimensionCount);
        using TestVectorStoreWriterWithMetadata writer = new(collection);

        IngestionDocument document = new(documentId);
        IngestionChunk chunk = TestChunkFactory.CreateChunk("some content", document);
        chunk.Metadata["Classification"] = "important";

        List<IngestionChunk> chunks = [chunk];

        await writer.WriteAsync(chunks.ToAsyncEnumerable());

        TestChunkRecordWithMetadata record = await writer.VectorStoreCollection
            .GetAsync(filter: record => record.DocumentId == documentId, top: 1)
            .SingleAsync();

        Assert.NotNull(record);
        Assert.Equal(documentId, record.DocumentId);
        Assert.NotEmpty(record.SerializedContent);
        Assert.Equal("important", record.Classification);
    }

    [Fact]
    public async Task DoesSupportIncrementalIngestion()
    {
        string documentId = Guid.NewGuid().ToString();

        using TestEmbeddingGenerator<AIContent> testEmbeddingGenerator = new();
        using VectorStore vectorStore = CreateVectorStore(testEmbeddingGenerator);

        VectorStoreCollection<Guid, IngestionChunkVectorRecord> collection = vectorStore.GetIngestionRecordCollection<IngestionChunkVectorRecord>(
            "chunks-incr", TestEmbeddingGenerator<AIContent>.DimensionCount);

        using VectorStoreWriter<IngestionChunkVectorRecord> writer = new(
            collection,
            options: new()
            {
                IncrementalIngestion = true,
            });

        IngestionDocument document = new(documentId);
        IngestionChunk chunk1 = TestChunkFactory.CreateChunk("first chunk", document);
        IngestionChunk chunk2 = TestChunkFactory.CreateChunk("second chunk", document);

        List<IngestionChunk> chunks = [chunk1, chunk2];

        await writer.WriteAsync(chunks.ToAsyncEnumerable());

        int recordCount = await writer.VectorStoreCollection
            .GetAsync(filter: record => record.DocumentId == documentId, top: 100)
            .CountAsync();
        Assert.Equal(chunks.Count, recordCount);

        // Now we will do an incremental ingestion that updates the chunk(s).
        IngestionChunk updatedChunk = TestChunkFactory.CreateChunk("different content", document);

        List<IngestionChunk> updatedChunks = [updatedChunk];

        await writer.WriteAsync(updatedChunks.ToAsyncEnumerable());

        // We ask for 100 records, but we expect only 1 as the previous 2 should have been deleted.
        IngestionChunkVectorRecord record = await writer.VectorStoreCollection
            .GetAsync(filter: record => record.DocumentId == documentId, top: 100)
            .SingleAsync();

        Assert.NotNull(record);
        Assert.NotEqual(Guid.Empty, record.Key);
        Assert.Contains("different content", record.SerializedContent);
    }

    public static TheoryData<int?, int[]> BatchingTestCases => new()
    {
        // Low limit: BatchTokenCount=1, each chunk upserted separately
        { 1, [10, 10, 10] },

        // Default limit: chunks fit in single batch
        { null, [1000, 1000, 1000] },

        // Single chunk exceeds limit
        { 100, [200, 10] },

        // Multiple batches needed
        { 100, [60, 60, 60, 60] }
    };

    [Theory]
    [MemberData(nameof(BatchingTestCases))]
    public async Task BatchesChunks(int? batchTokenCount, int[] chunkTokenCounts)
    {
        string documentId = Guid.NewGuid().ToString();

        using TestEmbeddingGenerator<AIContent> testEmbeddingGenerator = new();
        using VectorStore vectorStore = CreateVectorStore(testEmbeddingGenerator);

        VectorStoreWriterOptions options = new() { IncrementalIngestion = false };
        if (batchTokenCount.HasValue)
        {
            options.BatchTokenCount = batchTokenCount.Value;
        }

        VectorStoreCollection<Guid, IngestionChunkVectorRecord> collection = vectorStore.GetIngestionRecordCollection<IngestionChunkVectorRecord>(
            "chunks-batch", TestEmbeddingGenerator<AIContent>.DimensionCount);

        using VectorStoreWriter<IngestionChunkVectorRecord> writer = new(
            collection,
            options: options);

        IngestionDocument document = new(documentId);
        List<IngestionChunk> chunks = [];
        for (int i = 0; i < chunkTokenCounts.Length; i++)
        {
            chunks.Add(new(new TextContent($"chunk {i + 1}"), document, context: null, tokenCount: chunkTokenCounts[i]));
        }

        await writer.WriteAsync(chunks.ToAsyncEnumerable());

        int recordCount = await writer.VectorStoreCollection
            .GetAsync(filter: record => record.DocumentId == documentId, top: 100)
            .CountAsync();

        Assert.Equal(chunks.Count, recordCount);
    }

    [Fact]
    public async Task IncrementalIngestion_WithManyRecords_DeletesAllPreExistingChunks()
    {
        string documentId = Guid.NewGuid().ToString();

        using TestEmbeddingGenerator<AIContent> testEmbeddingGenerator = new();
        using VectorStore vectorStore = CreateVectorStore(testEmbeddingGenerator);

        VectorStoreCollection<Guid, IngestionChunkVectorRecord> collection = vectorStore.GetIngestionRecordCollection<IngestionChunkVectorRecord>(
            "chunks-many", TestEmbeddingGenerator<AIContent>.DimensionCount);

        using VectorStoreWriter<IngestionChunkVectorRecord> writer = new(
            collection,
            options: new()
            {
                IncrementalIngestion = true,
            });

        IngestionDocument document = new(documentId);

        // Create enough chunks to exercise the incremental ingestion delete-all behavior in DEBUG builds
        List<IngestionChunk> chunks = [];
        for (int i = 0; i < 50; i++)
        {
            chunks.Add(TestChunkFactory.CreateChunk($"chunk {i}", document));
        }

        await writer.WriteAsync(chunks.ToAsyncEnumerable());

        int recordCount = await writer.VectorStoreCollection
            .GetAsync(filter: record => record.DocumentId == documentId, top: 10000)
            .CountAsync();
        Assert.Equal(chunks.Count, recordCount);

        // Now we will do an incremental ingestion that should delete all pre-existing chunks
        List<IngestionChunk> updatedChunks =
        [
            TestChunkFactory.CreateChunk("updated chunk 1", document),
            TestChunkFactory.CreateChunk("updated chunk 2", document)
        ];

        await writer.WriteAsync(updatedChunks.ToAsyncEnumerable());

        // Verify that all old records were deleted and only the new ones remain
        List<IngestionChunkVectorRecord> records = await writer.VectorStoreCollection
            .GetAsync(filter: record => record.DocumentId == documentId, top: 10000)
            .ToListAsync();

        Assert.Equal(updatedChunks.Count, records.Count);
        Assert.Contains(records, r => r.SerializedContent.Contains("updated chunk 1"));
        Assert.Contains(records, r => r.SerializedContent.Contains("updated chunk 2"));
    }

    protected abstract VectorStore CreateVectorStore(TestEmbeddingGenerator<AIContent> testEmbeddingGenerator);
}
