// <auto-generated />
namespace Microsoft.AspNet.ConfigurationModel.Json
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.AspNet.ConfigurationModel.Json.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// File path must be a non-empty string.
        /// </summary>
        internal static string Error_InvalidFilePath
        {
            get { return GetString("Error_InvalidFilePath"); }
        }

        /// <summary>
        /// File path must be a non-empty string.
        /// </summary>
        internal static string FormatError_InvalidFilePath()
        {
            return GetString("Error_InvalidFilePath");
        }

        /// <summary>
        /// Only an object can be the root. Path '{0}', line {1} position {2}.
        /// </summary>
        internal static string Error_RootMustBeAnObject
        {
            get { return GetString("Error_RootMustBeAnObject"); }
        }

        /// <summary>
        /// Only an object can be the root. Path '{0}', line {1} position {2}.
        /// </summary>
        internal static string FormatError_RootMustBeAnObject(object p0, object p1, object p2)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("Error_RootMustBeAnObject"), p0, p1, p2);
        }

        /// <summary>
        /// Unexpected end when parsing JSON. Path '{0}', line {1} position {2}.
        /// </summary>
        internal static string Error_UnexpectedEnd
        {
            get { return GetString("Error_UnexpectedEnd"); }
        }

        /// <summary>
        /// Unexpected end when parsing JSON. Path '{0}', line {1} position {2}.
        /// </summary>
        internal static string FormatError_UnexpectedEnd(object p0, object p1, object p2)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("Error_UnexpectedEnd"), p0, p1, p2);
        }

        /// <summary>
        /// Unsupported JSON token: '{0}'. Path '{1}', line {2} position {3}.
        /// </summary>
        internal static string Error_UnsupportedJSONToken
        {
            get { return GetString("Error_UnsupportedJSONToken"); }
        }

        /// <summary>
        /// Unsupported JSON token: '{0}'. Path '{1}', line {2} position {3}.
        /// </summary>
        internal static string FormatError_UnsupportedJSONToken(object p0, object p1, object p2, object p3)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("Error_UnsupportedJSONToken"), p0, p1, p2, p3);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
