// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using System.Threading.Tasks;

namespace Microsoft.Extensions.AI;

/// <summary>Represents a real-time session.</summary>
/// <remarks>This interface provides methods to manage a real-time session and to interact with the real-time model.</remarks>
[Experimental("MEAI001")]
public interface IRealtimeSession : IDisposable
{
    /// <summary>Updates the session with new options.</summary>
    /// <param name="options">The new session options.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A task that represents the asynchronous update operation.</returns>
    Task UpdateAsync(RealtimeSessionOptions options, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the current session options.
    /// </summary>
    RealtimeSessionOptions? Options { get; }

    /// <summary>
    /// Injects a client message into the session.
    /// </summary>
    /// <param name="message">The client message to inject.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A task that represents the asynchronous injection operation.</returns>
    /// <remarks>
    /// This method allows for the injection of client messages into the session at any time, which can be used to influence the session's behavior or state.
    /// </remarks>
    Task InjectClientMessageAsync(RealtimeClientMessage message, CancellationToken cancellationToken = default);

    /// <summary>Sends real-time messages and streams the response.</summary>
    /// <param name="updates">The sequence of real-time messages to send.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The response messages generated by the session.</returns>
    /// <remarks>
    /// This method cannot be called multiple times concurrently on the same session instance.
    /// </remarks>
    IAsyncEnumerable<RealtimeServerMessage> GetStreamingResponseAsync(
            IAsyncEnumerable<RealtimeClientMessage> updates, CancellationToken cancellationToken = default);

    /// <summary>Asks the <see cref="IRealtimeSession"/> for an object of the specified type <paramref name="serviceType"/>.</summary>
    /// <param name="serviceType">The type of object being requested.</param>
    /// <param name="serviceKey">An optional key that can be used to help identify the target service.</param>
    /// <returns>The found object, otherwise <see langword="null"/>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="serviceType"/> is <see langword="null"/>.</exception>
    /// <remarks>
    /// The purpose of this method is to allow for the retrieval of strongly typed services that might be provided by the <see cref="IRealtimeSession"/>,
    /// including itself or any services it might be wrapping.
    /// </remarks>
    object? GetService(Type serviceType, object? serviceKey = null);
}
