# For more info on HTTP files go to https://aka.ms/vs/httpfile

@HostAddress = http://localhost:9996

POST {{HostAddress}}/
Accept: application/json, text/event-stream
Content-Type: application/json
MCP-Protocol-Version: 2025-11-25

{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "tools/call",
    "params": {
        "name": "get_random_number"
    }
}
