name: Inter-branch merge workflow
on:
  push:
    branches:
      - release/**
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  Merge:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@main